### ISSUE TITLE
issue with suez integration

### ISSUE THREAD

**Issue by stivxgamer** [Jezza34000/home-assistant-veolia#3]
Adding the integration and the connection goes smoothly. But it is impossible to add to the "energy" tab. No entities available

![image](https://github.com/user-attachments/assets/f579f891-6cd1-4945-9e96-308a4d1d632b)

`Enregistreur: homeassistant.components.sensor
Source: helpers/entity_platform.py:728
intégration: Capteur (documentation, problèmes)
S'est produit pour la première fois: 18 novembre 2024 à 22:12:56 (2 occurrences)
Dernier enregistrement: 13:44:15

suez_water: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 728, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1304, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/suez_water/sensor.py", line 94, in update
    self._fetch_data()
  File "/usr/src/homeassistant/homeassistant/components/suez_water/sensor.py", line 57, in _fetch_data
    self.client.update()
  File "/usr/local/lib/python3.12/site-packages/pysuez/client.py", line 226, in update
    self._fetch_data()
  File "/usr/local/lib/python3.12/site-packages/pysuez/client.py", line 121, in _fetch_data
    self.state = int(float(data.json()[int(
                           ^^^^^^^^^^^^^^^^
IndexError: list index out of range`

**Comment by Jezza34000** [comment]
Hello,
Ce n'est pas mon intégration, merci de voir avec le propriétaire du repo concerné
